### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by letalvoj** [tim-group/iterata#2]
Could you please modify the script such that the lib get's cross-compiled to both 2.11 and 2.12? It'd be nice to have both versions on mvn.

**Comment by flicken** [comment]
Added cross compilation to build.sbt in 3b9b86f25af4c619ffae770fb16871c6fdf88733

Need get set up to deploy to Maven central, so it may be a few days before this is released.

**Comment by flicken** [comment]
Done.  See https://repo1.maven.org/maven2/com/timgroup/iterata_2.12/0.1.7/

**Comment by letalvoj** [comment]
Awesome! Thanks a lot. I'll check that out.
